call authContact.bat %1
call authSignup.bat %1
call catAll.bat %1
call catShow.bat %1
call classificationsSearch.bat %1
call companyDetails.bat %1
call companySave.bat %1
call companySearch.bat %1
call dcSummaries.bat %1
call domainTech.bat %1
call geocodeDistance.bat %1
call keywordsSearch.bat %1
call uniquify.bat %1
